apiVersion: v1
kind: ServiceAccount
metadata:
  name: spicedb
  namespace: spicedb
  labels:
    app.kubernetes.io/name: spicedb
    app.kubernetes.io/component: authorization
    app.kubernetes.io/part-of: secforge-platform
    secforge.platform/component: spicedb
automountServiceAccountToken: true
