#!/usr/bin/env bash
# bootstrap-app.sh — instantiate the app-namespace template for a new app.
#
# Reads APP_* env vars, renders templates from platform/templates/app-namespace/,
# applies them to the cluster, and creates the OpenBao K8s auth role that
# scopes the app's secrets access.
#
# Usage:
#   APP_NAME=proposal-forge \
#   APP_DOMAIN=pf.secforge.dev \
#   APP_CPU_REQ=200m APP_CPU_LIMIT=2 \
#   APP_MEM_REQ=512Mi APP_MEM_LIMIT=4Gi \
#   APP_OPENBAO_PATHS='secret/data/proposal-forge/*' \
#   APP_TRUSTED_NAMESPACES=keycloak,observability \
#     bash platform/components/bootstrap-app.sh
#
# Idempotent: re-running with the same APP_* vars updates resources in place.
#
# Pre-conditions:
#   - SecForge platform deployed (cert-manager, ingress-nginx, OpenBao,
#     SPIRE, Istio, VSO, observability, Kyverno).
#   - openbao-root-token-tmp Secret in openbao ns.
#
# Post-conditions:
#   - Namespace ${APP_NAME} exists with PSA restricted, Istio ambient,
#     default-deny + allow-list NPs, ResourceQuota + LimitRange,
#     SA + VaultAuth, ClusterSPIFFEID, AuthorizationPolicy.
#   - OpenBao K8s auth role ${APP_NAME}-vso bound to a per-app policy
#     that grants read on APP_OPENBAO_PATHS.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
PLATFORM_DIR="$(dirname "$SCRIPT_DIR")"
TEMPLATES_DIR="$PLATFORM_DIR/templates/app-namespace"

red()    { printf '\033[31m%s\033[0m\n' "$*" >&2; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }

# ─── Validate required parameters ─────────────────────────────────────
: "${APP_NAME:?APP_NAME is required (e.g., proposal-forge)}"
: "${APP_DOMAIN:?APP_DOMAIN is required (e.g., pf.secforge.dev)}"
: "${APP_CPU_REQ:=100m}"
: "${APP_CPU_LIMIT:=2}"
: "${APP_MEM_REQ:=256Mi}"
: "${APP_MEM_LIMIT:=4Gi}"
: "${APP_OPENBAO_PATHS:=}"
: "${APP_TRUSTED_NAMESPACES:=}"

# Quotas — set to 4× per-pod limits as a conservative cap. App can
# still scale up to 4 replicas at full limit, or many smaller replicas.
APP_CPU_REQ_QUOTA="${APP_CPU_REQ_QUOTA:-$(echo "$APP_CPU_LIMIT" | sed 's/[^0-9]//g; s/^$/2/')}"
APP_CPU_LIMIT_QUOTA="${APP_CPU_LIMIT_QUOTA:-$(echo "$APP_CPU_LIMIT" | awk '{n=$0; gsub(/[^0-9]/,"",n); print n*4}')}"
APP_MEM_REQ_QUOTA="${APP_MEM_REQ_QUOTA:-$(echo "$APP_MEM_LIMIT" | sed 's/Gi$//; s/Mi$//' | awk '{print $0*2"Gi"}')}"
APP_MEM_LIMIT_QUOTA="${APP_MEM_LIMIT_QUOTA:-$(echo "$APP_MEM_LIMIT" | sed 's/Gi$//; s/Mi$//' | awk '{print $0*4"Gi"}')}"

green "==> bootstrapping app namespace: $APP_NAME"
green "    domain:           $APP_DOMAIN"
green "    pod limits:       cpu=$APP_CPU_LIMIT mem=$APP_MEM_LIMIT"
green "    namespace quota:  cpu=$APP_CPU_LIMIT_QUOTA mem=$APP_MEM_LIMIT_QUOTA"
green "    OpenBao paths:    ${APP_OPENBAO_PATHS:-(none)}"
green "    trusted ns:       ${APP_TRUSTED_NAMESPACES:-(none)}"

# Export for envsubst
export APP_NAME APP_DOMAIN APP_CPU_REQ APP_CPU_LIMIT APP_MEM_REQ APP_MEM_LIMIT
export APP_CPU_REQ_QUOTA APP_CPU_LIMIT_QUOTA APP_MEM_REQ_QUOTA APP_MEM_LIMIT_QUOTA

ALLOW='${APP_NAME} ${APP_DOMAIN} ${APP_CPU_REQ} ${APP_CPU_LIMIT} ${APP_MEM_REQ} ${APP_MEM_LIMIT} ${APP_CPU_REQ_QUOTA} ${APP_CPU_LIMIT_QUOTA} ${APP_MEM_REQ_QUOTA} ${APP_MEM_LIMIT_QUOTA}'

# ─── 1-7. Render + apply each template file in order ──────────────────
for tpl in "$TEMPLATES_DIR"/*.yaml.tpl; do
  base="$(basename "$tpl" .tpl)"
  green "==> apply $base"
  envsubst "$ALLOW" < "$tpl" | kubectl apply -f -
done

# ─── 8. OpenBao policy + K8s auth role for this app ───────────────────
NS_BAO=openbao
POD_BAO=openbao-0

if ! kubectl -n "$NS_BAO" get secret openbao-root-token-tmp >/dev/null 2>&1; then
  yellow "    openbao-root-token-tmp Secret missing — skipping OpenBao role creation"
  yellow "    Re-run after pasting the root token; the app namespace is otherwise complete."
else
  ROOT_TOKEN=$(kubectl -n "$NS_BAO" get secret openbao-root-token-tmp -o jsonpath='{.data.token}' | base64 -d)
  bao() {
    kubectl exec -n "$NS_BAO" "$POD_BAO" -c openbao -- env BAO_SKIP_VERIFY=1 BAO_TOKEN="$ROOT_TOKEN" "$@"
  }

  # Per-app OpenBao policy. Reads-only on the explicit paths the app declared.
  green "==> write OpenBao policy: $APP_NAME"
  POLICY_HCL=$(cat <<EOF
# Per-app policy for $APP_NAME (auto-generated by bootstrap-app.sh).
# Grants read on the explicit KV paths declared by the app.
EOF
)
  if [ -n "$APP_OPENBAO_PATHS" ]; then
    IFS=',' read -ra PATHS <<< "$APP_OPENBAO_PATHS"
    for p in "${PATHS[@]}"; do
      p_trimmed="$(echo "$p" | xargs)"
      POLICY_HCL+=$(cat <<EOF


path "$p_trimmed" {
  capabilities = ["read"]
}
path "$(echo "$p_trimmed" | sed 's|secret/data/|secret/metadata/|')" {
  capabilities = ["read"]
}
EOF
)
    done
  fi

  # `kubectl exec` doesn't pipe stdin to the pod without -i, so the
  # `echo | bao policy write -` pattern silently sends an empty policy.
  # Stage the HCL via a temp file in the pod, then bao reads from there.
  TMP_HCL="/tmp/${APP_NAME}-policy.hcl"
  echo "$POLICY_HCL" | kubectl exec -i -n "$NS_BAO" "$POD_BAO" -c openbao -- sh -c "cat > $TMP_HCL"
  bao bao policy write "$APP_NAME" "$TMP_HCL" >/dev/null
  kubectl exec -n "$NS_BAO" "$POD_BAO" -c openbao -- rm -f "$TMP_HCL"

  # K8s auth role bound to the SA created by 07-vso-binding.yaml.tpl.
  K8S_AUDIENCE="https://kubernetes.default.svc.cluster.local"
  green "==> write OpenBao K8s auth role: $APP_NAME-vso"
  bao bao write "auth/kubernetes/role/$APP_NAME-vso" \
    bound_service_account_names="$APP_NAME-vso" \
    bound_service_account_namespaces="$APP_NAME" \
    audience="$K8S_AUDIENCE" \
    policies="$APP_NAME" \
    ttl="1h" \
    max_ttl="24h" 2>&1 | tail -1

  unset ROOT_TOKEN
fi

cat <<EOF

✓ App namespace $APP_NAME bootstrapped.

Inspect:
  kubectl get all -n $APP_NAME
  kubectl get networkpolicy,resourcequota,limitrange -n $APP_NAME
  kubectl get clusterspiffeid $APP_NAME-default
  bao policy read $APP_NAME

Next steps for the app's own Helm chart:
  - Set spec.serviceAccountName: app-default (or a chart-specific SA)
  - Label pods with secforge.platform/app: "true" (image-sig policy match)
  - Label pods with spiffe.io/spire-managed-identity: "true" (for SVID)
  - Mount SVID via csi.spiffe.io
  - Reference VSO-rendered Secrets (VaultStaticSecret resources point at
    OpenBao paths declared in APP_OPENBAO_PATHS)
  - Add per-route Istio AuthorizationPolicy ALLOW rules
EOF
