apiVersion: v1
kind: Service
metadata:
  name: helloworld-backend
  namespace: app
  labels:
    app.kubernetes.io/name: helloworld-backend
    secforge.platform/component: helloworld-backend
    app.kubernetes.io/part-of: helloworld
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: helloworld-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
